### ISSUE TITLE
2.4.0.0: --prefix containing a slash is split and the folder part is dropped on backends without folder support (regression from 2.3.0.4)

### ISSUE THREAD

**Issue by xsergos** [duplicati/duplicati#7271]
### Environment

- Duplicati **2.4.0.0_stable_2026-09-03** (Docker, `duplicati/duplicati`), upgraded from **2.3.0.4_stable_2026-07-09**
- Primary destination: Azure Blob (`azure://<container>`)
- Backup jobs use the advanced option `--prefix` with a `/` in the value, e.g. `--prefix=myjob/duplicati`, so remote volumes are named `myjob/duplicati-20260903T230007Z.dlist.zip.aes`. On Azure this yields a virtual folder per job inside one container. This worked for years up to and including 2.3.0.4.

### Symptom

Immediately after upgrading to 2.4.0.0, the first backup run of every job broke:

```
[Error-Duplicati.Library.Main.Operation.FilelistProcessor-MissingRemoteFiles]:
Found N files that are missing from the remote storage, please run repair
RemoteListVerificationException: Found N files that are missing from the remote storage, please run repair
```

`repair` reports success and uploads a dlist, and a `test` nine seconds later says the very same file is missing:

```
23:23:22 [Information-...BasicResults-BackendEvent]: Backend event: Put - Completed: myjob/duplicati-20260903T230007Z.dlist.zip.aes (1,731 KiB)
23:23:31 [Warning-...FilelistProcessor-MissingFile]:  Missing file: myjob/duplicati-20260903T230007Z.dlist.zip.aes
23:23:31 [Error-...FilelistProcessor-MissingRemoteFiles]: Found 1 files that are missing from the remote storage, please run repair
```

Inspecting the storage shows why: volumes written since the upgrade land at the **root of the container/bucket** with the folder part of the name stripped (`duplicati-20260903T230007Z.dlist.zip.aes`), while every volume written before the upgrade is correctly inside `myjob/`. The local database still records the full name `myjob/duplicati-...`, so it can never find them again.

Jobs that had nothing new to upload on the night of the upgrade are unaffected until their first run with actual changes.

### Root cause

`ApplyPathTranslation` is new in 2.4.0.0 — `Duplicati/Library/Main/Backend/BackendManager.cs:234-250`:

```csharp
private void ApplyPathTranslation(PendingOperationBase op)
{
    if (supportsFolderOperations.Value)
        return; // Folder-enabled backends take the full relative path directly.

    var relPath = op.RemoteFilename;
    var lastSlash = relPath.LastIndexOf('/');
    if (lastSlash < 0)
        return;

    var subPath  = relPath.Substring(0, lastSlash);
    var filename = relPath.Substring(lastSlash + 1);

    op.BackendUrlOverride = MergeBackendPath(subPath);
    op.EffectiveRemoteName = filename;
}
```

It is called unconditionally from the ordinary backup upload path, `BackendManager.cs:466`:

```csharp
op.StartEncryptionAndHashing();
ApplyPathTranslation(op);          // new in 2.4.0.0
await QueueTaskAsync(op).ConfigureAwait(false);
```

The 2.3.0.4 counterpart (`BackendManager.cs:315-317`) has no such call; `ApplyPathTranslation`, `MergeBackendPath` and `IFolderEnabledBackend` do not appear in that file at all.

For a backend that does not implement `IFolderEnabledBackend` the folder part is supposed to come back via the URL override. **The Azure backend ignores the URL path entirely** — `Duplicati/Library/Backend/AzureBlob/AzureBlobBackend.cs:112-114` reads only the host as the container name and never looks at `uri.Path`:

```csharp
var uri = new Utility.Uri(url);
uri.RequireHost();
var containerName = (uri.Host ?? "").ToLowerInvariant();
```

So `MergeBackendPath` turning `azure://container` into `azure://container/myjob` is a no-op, and the blob is created at the container root under the bare filename.

Meanwhile the database is updated with the *unsplit* name — `BackendManager.PutOperation.cs:286, 302, 317`:

```csharp
var effectiveName = GetEffectiveRemoteName();   // "duplicati-2026....dlist.zip.aes"
...
await streamingBackend.PutAsync(effectiveName, pgs, cancelToken)...
...
Context.Database.LogRemoteVolumeUpdated(RemoteFilename, RemoteVolumeState.Uploaded, size, hash);  // "myjob/duplicati-..."
```

The post-put verification at `PutOperation.cs:328` compares against `effectiveName`, so the misplaced upload validates and the run looks clean — the failure only surfaces on the next list.

The folder machinery was introduced by PR #6988 (commit `62ea2d23`, "Added a sync command to the Controller and CLI"), whose intended consumer is the new `Operation/Sync/SyncHandler.cs`, the only caller that passes a non-null path. Applying it unconditionally in `PutAsync` / `PutFileUnencryptedAsync` / `Get*` / `DeleteAsync` makes it fire for ordinary backups as well.

### Knock-on effect with multiple destinations

With the multiple-destinations feature, `RemoteSynchronizationRunner.CopyAsync` copies verbatim by source listing name (`RemoteSynchronizationRunner.cs:420/450`, `b_src.GetAsync(f.Name)` / `b_dst.PutAsync(f.Name)`), and `LightWeightBackendManager` applies no translation. Since the primary now lists the stripped names, the secondary destination (S3/MinIO in our case) also receives them at bucket root, mixing the volumes of several jobs that previously lived in separate folders.

### Expected vs actual

- **Expected:** a `--prefix` containing `/` keeps producing the same remote volume names it produced in 2.3.0.4, and the names written to the backend match the names recorded in the local database.
- **Actual:** the name is split, the folder part is silently dropped on backends that ignore the URL path, and the database and the storage disagree from the first upload onward.

Documentation describes `--prefix` as a filename prefix ("can be used to store multiple backups in the same remote folder") and only forbids `-`, so a `/` in the value is not rejected anywhere; it has been a working way to separate jobs on backends without folder support.

### Suggested fix

Apply `ApplyPathTranslation` only for operations that were given an explicit path (i.e. the `sync` operation), not to every backup upload. Alternatively, skip the translation when the backend cannot honour the resulting URL path, so that the full name is passed through as before.

### Impact

Silent. Backups appear to succeed, the local database and the remote storage diverge from the first upload, and the breakage is only discovered on the next verification. Recovering requires moving the misplaced objects back into their folder on every destination.

**Comment by kenkendk** [comment]
I think we should fix the regression, but the intention with `--prefix` was mostly to allow multiple backups to co-exist in the same folder. The distinction between folder and prefix is a bit blurry for an object storage where it is technically not a folder by a prefix.

If you remove the `--prefix` option then you need the destination to be `azure://<container>/myjob/` and the path will resolve correctly.

**Comment by xsergos** [comment]
Thanks for the quick response, and good to hear the regression will be fixed.

One note on the suggested workaround: it does not work for the Azure backend today. `AzureBlobBackend.cs:112-114` uses only the host component as the container name and never reads `uri.Path`:

```csharp
var uri = new Utility.Uri(url);
uri.RequireHost();
var containerName = (uri.Host ?? "").ToLowerInvariant();
```

`AzureBlobWrapper` takes no prefix/path parameter either, so `azure://<container>/myjob` resolves to `azure://<container>` and the volumes land at the container root. That is the same reason the `BackendUrlOverride` produced by `ApplyPathTranslation` is a no-op here.

So on Azure, a `--prefix` containing `/` has been the only way to keep several jobs apart within one container — relevant when the SAS/credentials are scoped to a single container and creating more containers is not in the backup user's hands.

Two things that would each solve it, and they are complementary:

1. The regression fix: pass the full relative name through unchanged for backends that are not `IFolderEnabledBackend`, instead of splitting it and relying on a URL override the backend may ignore.
2. Make `AzureBlob` honour the URL path — either implement `IFolderEnabledBackend`, or prepend the path to the blob name — so the documented `azure://<container>/<prefix>` form actually works and the workaround becomes real.

One more data point on severity: `ApplyPathTranslation` is also applied to `DeleteAsync`, so retention deletes were issued against the stripped names and silently did nothing. The volumes stayed on the remote while the database marked them deleted; that only surfaced after downgrading, when the next run reported ~100 extra unknown files per job and removed them. So the divergence grows in both directions, not just on upload.

Happy to test a canary build against the Azure + multi-destination setup.

**Comment by kenkendk** [comment]
@xsergos The canary build is out now and it should fix both the regression and introduces the "right way" to specify a subfolder in Azure. Please re-open or create a new issue if there are still problems.
